# Generated by Django 2.2.5 on 2019-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lpz2019V1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('measurementday', models.TextField(blank=True, db_column='Measurementday', null=True)),
                ('ward_name', models.TextField(blank=True, db_column='Ward_name', null=True)),
                ('ward_type', models.TextField(blank=True, db_column='Ward_type', null=True)),
                ('d_num_clients_part', models.IntegerField(blank=True, db_column='D_Num_clients_part', null=True)),
                ('d_num_clients_beh', models.IntegerField(blank=True, db_column='D_Num_clients_beh', null=True)),
                ('qf_ward_pu_discussed', models.TextField(blank=True, db_column='QF_Ward_PU_Discussed', null=True)),
                ('qf_ward_pu_discussed_afd', models.FloatField(blank=True, db_column='QF_Ward_PU_Discussed_afd', null=True)),
                ('pu_prev', models.FloatField(blank=True, db_column='PU_Prev', null=True)),
                ('pu_prev_ward', models.FloatField(blank=True, db_column='PU_Prev_ward', null=True)),
                ('med_fouten', models.TextField(blank=True, db_column='Med_fouten', null=True)),
                ('med_fouten_ward_nee', models.FloatField(blank=True, db_column='Med_fouten_ward_nee', null=True)),
                ('med_fouten_ward_ja_nietmultid', models.FloatField(blank=True, db_column='Med_fouten_ward_ja_nietmultid', null=True)),
                ('med_fouten_ward_ja', models.FloatField(blank=True, db_column='Med_fouten_ward_ja', null=True)),
                ('med_review', models.TextField(blank=True, db_column='Med_review', null=True)),
                ('med_review_ward', models.FloatField(blank=True, db_column='Med_review_ward', null=True)),
                ('acp_reanimeren', models.FloatField(blank=True, db_column='ACP_reanimeren', null=True)),
                ('acp_reanimeren_ward', models.FloatField(blank=True, db_column='ACP_reanimeren_ward', null=True)),
                ('acp_lifeending', models.FloatField(blank=True, db_column='ACP_lifeending', null=True)),
                ('acp_lifeending_ward', models.FloatField(blank=True, db_column='ACP_lifeending_ward', null=True)),
                ('acp_ziekenhuis', models.FloatField(blank=True, db_column='ACP_ziekenhuis', null=True)),
                ('acp_ziekenhuis_ward', models.FloatField(blank=True, db_column='ACP_ziekenhuis_ward', null=True)),
                ('acp_anders', models.FloatField(blank=True, db_column='ACP_anders', null=True)),
                ('acp_anders_ward', models.FloatField(blank=True, db_column='ACP_anders_ward', null=True)),
                ('vbm_mechanisch', models.FloatField(blank=True, db_column='VBM_Mechanisch', null=True)),
                ('vbm_mechanisch_ward', models.FloatField(blank=True, db_column='VBM_Mechanisch_ward', null=True)),
                ('vbm_elektronisch', models.FloatField(blank=True, db_column='VBM_elektronisch', null=True)),
                ('vbm_elektronisch_ward', models.FloatField(blank=True, db_column='VBM_elektronisch_ward', null=True)),
                ('vbm_fysiek', models.FloatField(blank=True, db_column='VBM_fysiek', null=True)),
                ('vbm_fysiek_ward', models.FloatField(blank=True, db_column='VBM_fysiek_ward', null=True)),
                ('vbm_1op1toezicht', models.IntegerField(blank=True, db_column='VBM_1op1toezicht', null=True)),
                ('vbm_1op1toezicht_ward', models.IntegerField(blank=True, db_column='VBM_1op1toezicht_ward', null=True)),
                ('vbm_farmacologisch', models.FloatField(blank=True, db_column='VBM_farmacologisch', null=True)),
                ('vbm_farmacologisch_ward', models.FloatField(blank=True, db_column='VBM_farmacologisch_ward', null=True)),
                ('vbm_psychologisch', models.IntegerField(blank=True, db_column='VBM_psychologisch', null=True)),
                ('vbm_psychologisch_ward', models.IntegerField(blank=True, db_column='VBM_psychologisch_ward', null=True)),
                ('vbm_afzondering', models.IntegerField(blank=True, db_column='VBM_afzondering', null=True)),
                ('vbm_afzondering_ward', models.IntegerField(blank=True, db_column='VBM_afzondering_ward', null=True)),
                ('vbm_overig', models.FloatField(blank=True, db_column='VBM_overig', null=True)),
                ('vbm_overig_ward', models.FloatField(blank=True, db_column='VBM_overig_ward', null=True)),
            ],
            options={
                'db_table': 'LPZ2019V1',
                'managed': False,
            },
        ),
    ]
